### ISSUE TITLE
2.5.0 has a breaking change

### ISSUE THREAD

**Issue by kyleabens** [eakoriakin/ionic-select-searchable#73]
There is a breaking change with 2.5.0 and it has to deal with placing `<select-searchable>` within a modal and utilizing infinite scrolling and updating the existing data in someway.  If placed within a modal the new data is never rendered.  If you change from displaying the page as a modal to a standard page by pushing it with the NavController then it works fine.

**Comment by kyleabens** [comment]
I have finally narrowed it down to the issue being cause by placing the searchable component in a modal.  If It's in a standard page it works fine but when accessing from modal the data does not update.  I'll work on creating a stackblitz for you.

**Comment by eakoriakin** [comment]
Hey, thanks for a detailed info, I’ll ckechk it soon

**Comment by kyleabens** [comment]
@eakoriakin  Here ya go.  

https://stackblitz.com/edit/ionic-select-searchable-infinite-scroll-n7f9ht

I just copied your infinite scroll demo and placed it within a modal.  If you scroll to the bottom you'll notice that it doesn't work.

**Comment by eakoriakin** [comment]
Hey, I've been working on the issue and I think fixed it, just need to do a couple more tests and I'll publish a new version maybe by the end of the day.

**Comment by eakoriakin** [comment]
I've fixed the issue. Try a new [2.8.0](https://github.com/eakoriakin/ionic-select-searchable/releases/tag/2.8.0) release.

**Comment by kyleabens** [comment]
Thanks for the quick turn around!  I'm getting the following error now with 2.8.0 when I open the searchable component.  The data being populated within this component is coming from an api.  I'm sure that has something to do with it but I'm still seeing if I can pin point this issue.

<img width="646" alt="screen shot 2018-07-18 at 4 27 20 pm" src="https://user-images.githubusercontent.com/25699262/42906615-9e430c9e-8aa9-11e8-9eb8-d1e2b115f051.png">

**Comment by kyleabens** [comment]
I found the problem.  I was able to fix it by going into ion-select-searchable.umd.js and checking to see if `selectComponent._filteredGroups` exists before I check its length for each *ngIf that does so.  Here is each one I had to update:

`*ngIf=\"!selectComponent.hasVirtualScroll && selectComponent._filteredGroups && selectComponent._filteredGroups.length\"`

`*ngIf=\"selectComponent.hasVirtualScroll && selectComponent._filteredGroups && selectComponent._filteredGroups.length\"`

`*ngIf=\"selectComponent._filteredGroups && (!selectComponent._filteredGroups.length || !selectComponent._filteredGroups[0].items.length)\"`

**Comment by kyleabens** [comment]
This fix may work when running the application in a browser or emulator but it fails when building for production.

**Comment by eakoriakin** [comment]
Hey, did you solve the problem or still need any help?
